---
# Disabling Ansible repo if it is enabled.

- name: Ansible Repo | Check if the Ansible repo is listed
  shell: yum repolist | grep -q '^ansible-2-for-rhel-8-x86_64-rpms'
  register: ansible_repo_check
  ignore_errors: true
  changed_when: false

- name: Ansible Repo | | Disable Ansible repo
  command: subscription-manager repos --disable=ansible-2-for-rhel-8-x86_64-rpms
  when: ansible_repo_check.rc == 0