---
- name: Hyperthreading | Create script to disable CPU hyperthreading
  copy:
    dest: "{{ hyperthreading_file }}"
    content: |
      #!/bin/sh
      for vcpu in $(cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | cut -s -d- -f2 | cut -d- -f2 | uniq); do
          echo "0" > "/sys/devices/system/cpu/cpu"$vcpu"/online"
      done
    mode: '0755'
  when: not enable_hyperthreading

- name: Hyperthreading | Execute hyperthreading disable script
  shell: "{{ hyperthreading_file }}"
  when: not enable_hyperthreading

- name: Hyperthreading | Ensure script runs on reboot via cron
  cron:
    name: "Disable Hyperthreading"
    special_time: reboot
    job: "{{ hyperthreading_file }}"
  when: not enable_hyperthreading
