---

# Configure VPC file share required for the cluster
- name: Configure VPC fileshare
  import_tasks: vpc_fileshare_configure.yml

# Setup passwordless SSH authentication for lsfadmin user across nodes
- name: Configure passwordless SSH for lsfadmin
  import_tasks: lsfadmin_password_less_auth.yml

# Disable hyperthreading on compute nodes for better HPC performance
- name: Disable CPU hyperthreading
  import_tasks: disable_hyperthreading.yml

# Load Cluster specific variables
- name: Load Cluster specific variables
  import_tasks: load_cluster_variables.yml
  when:
    - inventory_hostname in groups['management_nodes']
