---
apiVersion: v1
offerings:

# below is an example of a Deployable Architecture (DA) solution
- name: IBM Cloud HPC (DA) # must match the offering name in the ibm_catalog.json
  kind: solution
  catalog_id: fe9d2e76-5ada-44af-821f-b437dcc80f71
  offering_id: 468c5a1c-1f1d-4e5a-b5b3-ec646b1bd298
  # list all of the variations (flavors) you have included in the ibm_catalog.json
  variations:
    - name: standard
      mark_ready: false # have pipeline mark as visable if validation passes
      install_type: fullstack # ensure value matches what is in ibm_catalog.json (fullstack or extension)
      destroy_resources_on_failure: false # defaults to false if not specified so resources can be inspected to debug failures during validation
      destroy_workspace_on_failure: false # defaults to false if not specified so schematics workspace can be inspected to debug failures during validation
      import_only: false  # defaults to false - set to true if you do not want to do any validation, but be aware offering can't be publish if not validated
      validation_rg: validation # the resource group in which to do validation in. Will be created if does not exist. If not specified, default value is 'validation'
      # scc details needed if your offering is claiming any compliance controls
      scc:
        # must be an instance in the same account the validation is being done in
        instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
        region: us-south
      # pre_validation: tests/scripts/pre-validation.sh # optionally run a command before validation runs
      # post_validation: tests/scripts/post-validation.sh  # optionally run a command after validation completes