module "hpc" {
  source                     = "./solutions/hpc"
  allowed_cidr               = var.remote_allowed_ips
  # bootstrap_instance_profile = var.bootstrap_instance_profile
  bastion_ssh_keys           = var.bastion_ssh_keys
  bastion_subnets_cidr       = var.vpc_cluster_login_private_subnets_cidr_blocks
  #compute_gui_password          = var.compute_gui_password
  #compute_gui_username          = var.compute_gui_username
  compute_image_name        = var.compute_image_name
  compute_ssh_keys          = var.compute_ssh_keys
  compute_subnets_cidr      = var.vpc_cluster_private_subnets_cidr_blocks
  cos_instance_name         = var.cos_instance_name
  #dns_custom_resolver_id    = var.dns_custom_resolver_id
  dns_instance_id           = var.dns_instance_id
  dns_domain_names          = var.dns_domain_names
  # dynamic_compute_instances = var.dynamic_compute_instances
  # enable_atracker           = var.enable_atracker
  # enable_bastion            = var.enable_bastion
  # enable_bootstrap          = var.enable_bootstrap
  enable_cos_integration    = var.enable_cos_integration
  enable_vpc_flow_logs      = var.enable_vpc_flow_logs
  enable_vpn                = var.vpn_enabled
  file_shares               = var.custom_file_shares
  # hpcs_instance_name        = var.hpcs_instance_name
  #ibm_customer_number       = var.ibm_customer_number
  ibmcloud_api_key          = var.ibmcloud_api_key
  key_management            = var.key_management
  # login_image_name          = var.login_image_name
  # login_instances           = var.login_instances
  # login_ssh_keys            = var.login_ssh_keys
  #login_subnets_cidr       = var.login_subnets_cidr
  management_image_name = var.management_image_name
  # management_instances  = var.management_instances
  network_cidr          = var.vpc_cidr
  # nsd_details           = var.nsd_details
  # placement_strategy    = var.placement_strategy
  prefix                = var.cluster_prefix
  # protocol_instances    = var.protocol_instances
  # protocol_subnets_cidr = var.protocol_subnets_cidr
  resource_group        = var.resource_group
  #scheduler            = var.scheduler
  # static_compute_instances = var.static_compute_instances
  #storage_gui_password    = var.storage_gui_password
  #storage_gui_username    = var.storage_gui_username
  # storage_image_name   = var.storage_image_name
  # storage_instances    = var.storage_instances
  # storage_ssh_keys     = var.storage_ssh_keys
  # storage_subnets_cidr = var.storage_subnets_cidr
  #storage_type        = var.storage_type
  vpc               = var.vpc_name
  existing_subnet_cidrs = var.vpc_name != null && length(var.subnet_id) > 0 ? [data.ibm_is_subnet.existing_subnet[0].ipv4_cidr_block, data.ibm_is_subnet.existing_subnet[1].ipv4_cidr_block] : []
  subnet_id             = var.subnet_id
  # vpn_peer_address  = var.vpn_peer_address
  # peer_cidr_list     = var.peer_cidr_list
  # vpn_preshared_key = var.vpn_preshared_key
  zones             = var.zones
  contract_id       = var.contract_id
  cluster_id        = var.cluster_id
  # ssh_key_name = var.ssh_key_name
  management_node_count         = var.management_node_count
  management_node_instance_type = var.management_node_instance_type
  enable_fip = var.enable_fip
  TF_VALIDATION_SCRIPT_FILES = var.TF_VALIDATION_SCRIPT_FILES
  kms_instance_name = var.kms_instance_name
  kms_key_name = var.kms_key_name
  ldap_admin_password = var.ldap_vsi_osimage_name
  ldap_vsi_profile              = var.ldap_vsi_profile
  enable_ldap = var.enable_ldap
  ldap_user_name                = var.ldap_user_name
  ldap_user_password            = var.ldap_user_password
  ldap_server                   = var.ldap_server
  ldap_vsi_osimage_name         = var.ldap_vsi_osimage_name
  enable_app_center             = var.enable_app_center
  app_center_gui_pwd            = var.app_center_gui_pwd
  skip_iam_authorization_policy = var.skip_iam_authorization_policy
}
