locals {
  # schematics_inputs_path                           = "/tmp/.schematics/solution_terraform.auto.tfvars.json"
  vpc_availability_zones                           = jsonencode(var.vpc_availability_zones)
  compute_cluster_instance_ids                     = jsonencode(var.compute_cluster_instance_ids)
  compute_cluster_instance_private_ips             = jsonencode(var.compute_cluster_instance_private_ips)
  compute_cluster_instance_private_dns_ip_map      = jsonencode(var.compute_cluster_instance_private_dns_ip_map)
  compute_cluster_instance_names                   = jsonencode(var.compute_cluster_instance_names)
  storage_cluster_instance_ids                     = jsonencode(var.storage_cluster_instance_ids)
  storage_cluster_instance_private_ips             = jsonencode(var.storage_cluster_instance_private_ips)
  storage_cluster_instance_names                   = jsonencode(var.storage_cluster_instance_names)
  storage_cluster_with_data_volume_mapping         = jsonencode(var.storage_cluster_with_data_volume_mapping)
  storage_cluster_instance_private_dns_ip_map      = jsonencode(var.storage_cluster_instance_private_dns_ip_map)
  storage_cluster_desc_instance_ids                = jsonencode(var.storage_cluster_desc_instance_ids)
  storage_cluster_desc_instance_private_ips        = jsonencode(var.storage_cluster_desc_instance_private_ips)
  storage_cluster_desc_data_volume_mapping         = jsonencode(var.storage_cluster_desc_data_volume_mapping)
  storage_cluster_desc_instance_private_dns_ip_map = jsonencode(var.storage_cluster_desc_instance_private_dns_ip_map)
  protocol_cluster_instance_names                  = jsonencode(var.protocol_cluster_instance_names)
  client_cluster_instance_names                    = jsonencode(var.client_cluster_instance_names)
  protocol_cluster_reserved_names                  = jsonencode(var.protocol_cluster_reserved_names)
  interface                                        = jsonencode(var.interface)
  export_ip_pool                                   = jsonencode(var.export_ip_pool)
  filesets                                         = jsonencode(var.filesets)
  afm_cos_bucket_details                           = jsonencode(var.afm_cos_bucket_details)
  afm_config_details                               = jsonencode(var.afm_config_details)
  afm_cluster_instance_names                       = jsonencode(var.afm_cluster_instance_names)
}
