---

# Install required LDAP client packages for integration

- name: LDAP | Determine RHEL major version for package compatibility
  ansible.builtin.shell: "grep -oE 'release [0-9]+' /etc/redhat-release | awk '{print $2}'"
  register: rhel_version
  changed_when: false

- name: LDAP | Install required OpenLDAP and SSSD packages on RHEL 8/9
  ansible.builtin.dnf:
    name:
      - libnsl
      - libnsl2
      - openldap-clients
      - sssd
      - sssd-ldap
      - oddjob-mkhomedir
      - openssl-perl
      - authselect
    state: present
  when: rhel_version.stdout in ["8", "9"]
