---
- name: Management Config Templates | Deploy credentials configuration file
  template:
    src: "templates/credentials.j2"
    dest: "{{ LSF_RC_IC_CONF }}/credentials"
    mode: '0644'
  run_once: true

- name: Management Config Templates | Deploy IBM Cloud Gen2 configuration file
  template:
    src: "templates/ibmcloudgen2_config.json.j2"
    dest: "{{ LSF_RC_IC_CONF }}/ibmcloudgen2_config.json"
    mode: '0644'
  run_once: true

- name: Management Config Templates | Deploy IBM Cloud Gen2 templates definition
  template:
    src: "templates/ibmcloudgen2_templates.json.j2"
    dest: "{{ LSF_RC_IC_CONF }}/ibmcloudgen2_templates.json"
    mode: '0644'
  run_once: true

- name: Management Config Templates | Deploy host providers configuration
  template:
    src: "templates/hostProviders.json.j2"
    dest: "{{ LSF_CONF_FILE_PATH }}/resource_connector/hostProviders.json"
    mode: '0644'
  run_once: true

- name: Management Config Templates | Deploy user data initialization script
  template:
    src: "templates/user_data.sh"
    dest: "{{ LSF_RC_IC_CONF }}/user_data.sh"
    mode: '0644'
  run_once: true
