# LDAP Server Variables

LDAP_DIR: "/opt/LDAP"
LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}" #pragma: allowlist secret
LDAP_GROUP: "{{ prefix }}"
LDAP_USER: "{{ ldap_user_name }}"
LDAP_USER_PASSWORD: "{{ ldap_user_password }}" #pragma: allowlist secret
BASE_DN: "{{ ldap_basedns }}"
LDAP_SERVER_IP: "{{ ldap_server }}"
LDAP_CERT_FILES_DIR: "/opt/ibm/terraform-ibm-hpc/modules/ansible-roles/ldap_key"
OPENLDAP_SERVER_PKGS:
  - slapd
  - ldap-utils
