resource "local_sensitive_file" "prepare_tf_input" {
  count    = var.enable_deployer == true ? 1 : 0
  content  = <<EOT
{
  "scheduler": "${local.scheduler}",
  "ibmcloud_api_key": "${var.ibmcloud_api_key}",
  "app_center_gui_password": "${var.app_center_gui_password}",
  "lsf_version": "${var.lsf_version}",
  "github_token": "${var.github_token}",
  "resource_group_ids": ${local.resource_group_ids},
  "cluster_prefix": "${var.cluster_prefix}",
  "zones": ${local.zones},
  "enable_landing_zone": false,
  "enable_deployer": false,
  "existing_bastion_instance_name": ${local.existing_bastion_instance_name},
  "ssh_keys": ${local.list_ssh_keys},
  "storage_instances": ${local.list_storage_instances},
  "storage_servers": ${local.list_storage_servers},
  "storage_type": "${var.storage_type}",
  "management_instances": ${local.list_management_instances},
  "protocol_instances": ${local.list_protocol_instances},
  "colocate_protocol_instances": ${var.colocate_protocol_instances},
  "ibm_customer_number": "${local.ibm_customer_number}",
  "static_compute_instances": ${local.list_compute_instances},
  "dynamic_compute_instances": ${local.dynamic_compute_instances},
  "client_instances": ${local.list_client_instances},
  "enable_cos_integration": ${var.enable_cos_integration},
  "enable_atracker": ${var.enable_atracker},
  "enable_vpc_flow_logs": ${var.enable_vpc_flow_logs},
  "remote_allowed_ips": ${local.remote_allowed_ips},
  "vpc_name": "${var.vpc_name}",
  "storage_subnets": ${local.list_storage_subnets},
  "protocol_subnets": ${local.list_protocol_subnets},
  "cluster_subnet_ids": ${local.list_cluster_subnet_ids},
  "client_subnets": ${local.list_client_subnets},
  "login_subnet_id": ${local.list_login_subnet_ids},
  "dns_domain_names": ${local.dns_domain_names},
  "key_management": ${local.key_management},
  "kms_instance_name" : ${local.kms_instance_name},
  "kms_key_name": ${local.kms_key_name},
  "boot_volume_encryption_key": ${local.boot_volume_encryption_key},
  "existing_kms_instance_guid": ${local.existing_kms_instance_guid},
  "skip_iam_share_authorization_policy": ${var.skip_iam_share_authorization_policy},
  "dns_custom_resolver_id": ${local.dns_custom_resolver_id},
  "dns_instance_id": ${local.dns_instance_id},
  "bastion_security_group_id": "${var.bastion_security_group_id}",
  "existing_bastion_security_group_id": ${local.existing_bastion_security_group_id},
  "deployer_hostname": "${var.deployer_hostname}",
  "deployer_ip": "${var.deployer_ip}",
  "bastion_fip": "${var.bastion_fip}",
  "ldap_instance": ${local.list_ldap_instances},
  "enable_ldap": ${var.enable_ldap},
  "ldap_server": ${local.ldap_server},
  "ldap_basedns": ${local.ldap_basedns},
  "ldap_instance_key_pair": ${local.list_ldap_ssh_keys},
  "ldap_admin_password": "${var.ldap_admin_password}",
  "ldap_user_name": "${var.ldap_user_name}",
  "ldap_user_password": "${var.ldap_user_password}",
  "ldap_server_cert": ${jsonencode(var.ldap_server_cert)},
  "afm_instances": ${local.list_afm_instances},
  "afm_cos_config": ${local.afm_cos_config_details},
  "scale_encryption_enabled": ${var.scale_encryption_enabled},
  "scale_encryption_type": ${local.scale_encryption_type},
  "gklm_instance_key_pair": ${local.list_gklm_ssh_keys},
  "gklm_instances": ${local.list_gklm_instances},
  "scale_encryption_admin_password": "${local.scale_encryption_admin_password}",
  "filesystem_config": ${local.filesystem_config},
  "enable_hyperthreading": ${var.enable_hyperthreading},
  "scc_enable": ${var.scc_enable},
  "scc_profile": "${var.scc_profile}",
  "scc_location": "${var.scc_location}",
  "scc_cos_bucket": "${var.scc_cos_bucket}",
  "scc_cos_instance_crn": "${var.scc_cos_instance_crn}",
  "scc_event_notification_plan": "${var.scc_event_notification_plan}",
  "cloud_logs_data_bucket": ${var.cloud_logs_data_bucket},
  "cloud_metrics_data_bucket": ${var.cloud_metrics_data_bucket},
  "observability_logs_enable_for_management": ${var.observability_logs_enable_for_management},
  "observability_logs_enable_for_compute": ${var.observability_logs_enable_for_compute},
  "observability_enable_platform_logs": ${var.observability_enable_platform_logs},
  "observability_monitoring_enable": ${var.observability_monitoring_enable},
  "observability_monitoring_plan": "${var.observability_monitoring_plan}",
  "observability_logs_retention_period": ${var.observability_logs_retention_period},
  "observability_monitoring_on_compute_nodes_enable": ${var.observability_monitoring_on_compute_nodes_enable},
  "observability_enable_metrics_routing": ${var.observability_enable_metrics_routing},
  "observability_atracker_enable": ${var.observability_atracker_enable},
  "observability_atracker_target_type": "${var.observability_atracker_target_type}",
  "enable_dedicated_host": "${var.enable_dedicated_host}",
  "storage_security_group_id": "${local.storage_security_group_id}",
  "custom_file_shares": ${local.custom_file_shares},
  "login_instance": ${local.login_instance}
}
EOT
  filename = local.schematics_inputs_path
}
