LSF_TOP: "/opt/ibm/lsf"
LSF_CONF: "{{ LSF_TOP }}/conf"
LSF_LOGS: "{{ LSF_TOP }}/log"
LSF_CLUSTER_FILE: "{{ LSF_CONF }}/lsf.cluster.{{ prefix }}"
LSFADMIN_DIR: "/home/lsfadmin"
nfs_client_mount_path: "/mnt/lsf"
