LSF_CONF_FILE_PATH: "/opt/ibm/lsfsuite/lsf/conf"
LSF_CONF_FILE: "{{ LSF_CONF_FILE_PATH }}/lsf.conf"

# compute_public_key_content: "{{ compute_public_key_content }}"
# compute_private_key_content: "{{ compute_private_key_content }}"
LSF_RC_IC_CONF: "{{ LSF_CONF_FILE_PATH }}/resource_connector/ibmcloudgen2/conf"
cluster_prefix: "{{ my_cluster_name }}"
ManagementHostNames: "anand-da12-mgmt-4e4a-002 anand-da12-mgmt-4e4a-001"
LSF_LSBATCH_CONF: "{{ LSF_CONF_FILE_PATH }}/lsbatch/{{ cluster_prefix }}/configdir"
rc_cidr_block: "10.10.20.0/24"
LSF_HOSTS_FILE: "{{ LSF_CONF_FILE_PATH }}/hosts"
LSF_EGO_CONF_FILE: "{{ LSF_CONF_FILE }}/ego/{{ cluster_prefix }}/kernel/ego.conf"

VPC_APIKEY_VALUE: "xxxxxxx"
rc_maxNum: "rc_maxNumxx"
rc_ncores: "rc_ncoresxx"
rc_ncpus: "rc_ncpusxx"
rc_memInMB: "rc_memInMBxx"
imageID: "imageIDxx"
subnetID: "subnetIDxx"
vpcID: "vpcIDxx"
rc_profile: "rc_profilexx"
securityGroupID: "securityGroupIDxx"
rc_rg: "rc_rgxx"
sshkey_ID: "sshkey_IDxx"
regionName: "regionNamexx"
zoneName: 'zoneNamexx'