LSF_TOP: "/opt/ibm/lsf"
LSF_CONF_FILE_PATH: "/opt/ibm/lsf/conf"
LSF_CONF_FILE: "{{ LSF_CONF_FILE_PATH }}/lsf.conf"
LSF_RC_IC_CONF: "{{ LSF_CONF_FILE_PATH }}/resource_connector/ibmcloudgen2/conf"
LSF_LSBATCH_CONF: "{{ LSF_CONF_FILE_PATH }}/lsbatch/{{ prefix }}/configdir"
LSF_HOSTS_FILE: "{{ LSF_CONF_FILE_PATH }}/hosts"
LSF_EGO_CONF_FILE: "{{ LSF_CONF_FILE_PATH }}/ego/{{ prefix }}/kernel/ego.conf"
LSF_CLUSTER_FILE: "{{ LSF_CONF_FILE_PATH }}/lsf.cluster.{{ prefix }}"
LSF_SUITE: "/opt/ibm/lsfsuite"
LSF_EXT_CONF: "{{ LSF_SUITE }}/ext"
JS_PAC_SERVER_URL: "{{ LSF_EXT_CONF }}/ppm/conf/js.conf"
default_cluster_name: "HPCCluster"
nfs_client_mount_path: "/mnt/lsf"
LSF_LICENSE_SCHEDULER_FILE: "{{ LSF_CONF_FILE_PATH }}/lsf.licensescheduler"
enable_license_scheduler: "{{ enable_license_scheduler }}"
