module "lsf" {
  source                                        = "./../.."
  scheduler                                     = "LSF"
  zones                                         = var.zones
  remote_allowed_ips                            = var.remote_allowed_ips
  cluster_prefix                                = local.env.cluster_prefix
  ssh_keys                                      = local.env.ssh_keys
  existing_resource_group                       = local.env.existing_resource_group
  vpc_cluster_login_private_subnets_cidr_blocks = local.env.vpc_cluster_login_private_subnets_cidr_blocks
  login_subnet_id                               = local.env.login_subnet_id
  vpc_cluster_private_subnets_cidr_blocks       = local.env.vpc_cluster_private_subnets_cidr_blocks
  cluster_subnet_ids                            = local.env.cluster_subnet_ids
  cos_instance_name                             = local.env.cos_instance_name
  dns_custom_resolver_id                        = local.env.dns_custom_resolver_id
  dns_instance_id                               = local.env.dns_instance_id
  dns_domain_names                              = local.env.dns_domain_names
  dynamic_compute_instances                     = local.env.dynamic_compute_instances
  enable_bastion                                = local.env.enable_bastion
  bastion_image                                 = local.env.bastion_image
  bastion_instance_profile                      = local.env.bastion_instance_profile
  deployer_image                                = local.env.deployer_image
  deployer_instance_profile                     = local.env.deployer_instance_profile
  enable_cos_integration                        = local.env.enable_cos_integration
  enable_vpc_flow_logs                          = local.env.enable_vpc_flow_logs
  custom_file_shares                            = local.env.custom_file_shares
  storage_security_group_id                     = local.env.storage_security_group_id
  key_management                                = local.env.key_management
  management_instances                          = local.env.management_instances
  vpc_cidr                                      = local.env.vpc_cidr
  # placement_strategy                               = local.env.placement_strategy
  protocol_instances                               = local.env.protocol_instances
  protocol_subnets_cidr                            = [local.env.protocol_subnets_cidr]
  static_compute_instances                         = local.env.static_compute_instances
  storage_instances                                = local.env.storage_instances
  storage_servers                                  = local.env.storage_servers
  storage_subnets_cidr                             = [local.env.storage_subnets_cidr]
  vpc_name                                         = local.env.vpc_name
  kms_instance_name                                = local.env.kms_instance_name
  kms_key_name                                     = local.env.kms_key_name
  skip_iam_share_authorization_policy              = local.env.skip_iam_share_authorization_policy
  observability_atracker_enable                    = local.env.observability_atracker_enable
  observability_atracker_target_type               = local.env.observability_atracker_target_type
  observability_monitoring_enable                  = local.env.observability_monitoring_enable
  observability_monitoring_on_compute_nodes_enable = local.env.observability_monitoring_on_compute_nodes_enable
  observability_logs_enable_for_management         = local.env.observability_logs_enable_for_management
  observability_logs_enable_for_compute            = local.env.observability_logs_enable_for_compute
  observability_enable_platform_logs               = local.env.observability_enable_platform_logs
  observability_enable_metrics_routing             = local.env.observability_enable_metrics_routing
  observability_logs_retention_period              = local.env.observability_logs_retention_period
  observability_monitoring_plan                    = local.env.observability_monitoring_plan
  scc_enable                                       = local.env.scc_enable
  scc_profile                                      = local.env.scc_profile
  scc_location                                     = local.env.scc_location
  scc_event_notification_plan                      = local.env.scc_event_notification_plan
  skip_flowlogs_s2s_auth_policy                    = local.env.skip_flowlogs_s2s_auth_policy
  skip_iam_authorization_policy                    = local.env.skip_iam_authorization_policy
  skip_kms_s2s_auth_policy                         = local.env.skip_kms_s2s_auth_policy
  ibmcloud_api_key                                 = local.env.ibmcloud_api_key
  lsf_version                                      = local.env.lsf_version
  enable_hyperthreading                            = local.env.enable_hyperthreading
  enable_ldap                                      = local.env.enable_ldap
  ldap_basedns                                     = local.env.ldap_basedns
  ldap_admin_password                              = local.env.ldap_admin_password
  ldap_user_name                                   = local.env.ldap_user_name
  ldap_user_password                               = local.env.ldap_user_password
  ldap_server                                      = local.env.ldap_server
  ldap_server_cert                                 = local.env.ldap_server_cert
  ldap_instances                                   = local.env.ldap_instances
  enable_dedicated_host                            = local.env.enable_dedicated_host
  existing_bastion_instance_name                   = local.env.existing_bastion_instance_name
  existing_bastion_instance_public_ip              = local.env.existing_bastion_instance_public_ip
  existing_bastion_security_group_id               = local.env.existing_bastion_security_group_id
  existing_bastion_ssh_private_key                 = local.env.existing_bastion_ssh_private_key
  vpn_enabled                                      = local.env.vpn_enabled
  github_token                                     = local.env.github_token # Delete this variable before pushing to the public repository.

  # compute_gui_password                             = local.env.compute_gui_password
  # compute_gui_username                             = local.env.compute_gui_username
  # storage_gui_password                             = local.env.storage_gui_password
  # storage_gui_username                             = local.env.storage_gui_username
}
