---

# Restart the NetworkManager on deployer node
- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"