---

# tasks file for lsf_templates

- name: Create inventory file from template
  template:
    src: lsf-inventory.j2
    dest: "{{ inventory_path }}/lsf-inventory"
  # delegate_to: localhost
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"

- name: Create config file from template
  template:
    src: lsf-config.j2
    dest: "{{ inventory_path }}/lsf-config.yml"
  # delegate_to: localhost
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"

- name: Create all variable file from template
  template:
    src: lsf-all.j2
    dest: "{{ inventory_path }}/group_vars/all"
  # delegate_to: localhost
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"