---
# tasks file for lsf_templates

- name: LSF | FP14 | Create inventory file from template
  template:
    src: fp14-inventory.j2
    dest: "{{ inventory_path }}/lsf-inventory"
  delegate_to: localhost

  run_once: true
  when: lsf_version == "fixpack_14"

- name: LSF | FP14 | Create config file from template
  template:
    src: fp14-config.j2
    dest: "{{ inventory_path }}/lsf-config.yml"
  delegate_to: localhost
  run_once: true
  when: lsf_version == "fixpack_14"

- name: LSF | FP15 | Create inventory file from template
  template:
    src: fp15-inventory.j2
    dest: "{{ inventory_path }}/lsf-inventory"
  delegate_to: localhost
  run_once: true
  when: lsf_version == "fixpack_15"

- name: LSF | FP15 | Create config file from template
  template:
    src: fp15-config.j2
    dest: "{{ inventory_path }}/lsf-config.yml"
  delegate_to: localhost
  run_once: true
  when: lsf_version == "fixpack_15"

# Update deployer_hostname in group_vars/all for both FP14 and FP15
- name: LSF | Update deployer_hostname in group_vars/all
  ansible.builtin.lineinfile:
    path: "{{ inventory_path }}/group_vars/all"
    regexp: "^deployer_hostname: .*"
    line: "deployer_hostname: {{ lsf_deployer_hostname }}"
  delegate_to: localhost
  run_once: true
