---
# Installing required prerequisite packages for the LSF cluster creation.
- name: LSF | Check OS version for package installation
  ansible.builtin.shell: "grep -oE 'release [0-9]+' /etc/redhat-release | awk '{print $2}'"
  register: rhel_version
  changed_when: false

- name: LSF | Get installed packages
  package_facts:
    manager: auto

- name: LSF | Install missing lsof and ipmitool packages
  dnf:
    name: "{{ ['lsof', 'ipmitool'] | difference(ansible_facts.packages.keys() | list) }}"
    state: present
  when:
    - rhel_version.stdout in ['8', '9']
    - (['lsof', 'ipmitool'] | difference(ansible_facts.packages.keys() | list)) | length > 0

# Create the shared LSF directory
- name: LSF | Display the last directory
  debug:
    msg: "The last directory is: {{ lsf_dir }}"

- name: LSF | Create base directories for LSF configuration
  ansible.builtin.file:
    path: "/mnt/lsf/{{ lsf_dir }}"
    state: directory
    mode: "0777"
