network_interface: "eth0"
network_script_path: "/etc/sysconfig/network-scripts"
sysctl_conf: "/etc/sysctl.conf"
lsfadmin_ssh_path: "/home/lsfadmin/.ssh"
hyperthreading_file: "/root/lsf_hyperthreading"
LSF_TOP: "/opt/ibm/lsf"
nfs_client_mount_path: "/mnt/lsf"
default_cluster_name: "HPCCluster"
