---
# tasks/main.yml

# - name: Run LSF Config Test
#   ansible.builtin.shell: >
#     ansible-playbook -f 32 -i lsf-inventory lsf-config-test.yml
#   register: lsf_config_test_result
#   changed_when: false
#   failed_when: lsf_config_test_result.rc != 0
#   # delegate_to: localhost

# - name: Run LSF Predeploy Test
#   ansible.builtin.shell: >
#     ansible-playbook -f 32 -i lsf-inventory lsf-predeploy-test.yml
#   register: lsf_predeploy_test_result
#   changed_when: false
#   failed_when: lsf_predeploy_test_result.rc != 0
#   # delegate_to: localhost

# - name: Run LSF Deploy
#   ansible.builtin.shell: >
#     ansible-playbook -f 32 -i lsf-inventory lsf-deploy.yml
#   register: lsf_deploy_test_result
#   changed_when: false
#   failed_when: lsf_deploy_test_result.rc != 0
#   # delegate_to: localhost



- name: Run LSF Config Test
  ansible.builtin.shell: >
    ansible-playbook -f 32 -i lsf-inventory lsf-config-test.yml > config-test.log 2>&1
  args:
    chdir: "{{ playbook_path }}"
  register: lsf_config_test_result
  changed_when: false
  failed_when: lsf_config_test_result.rc != 0
  ignore_errors: no
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"
  async: 3600
  poll: 5

- name: Run LSF Predeploy Test
  ansible.builtin.shell: >
    ansible-playbook -f 32 -i lsf-inventory lsf-predeploy-test.yml >> predeploy.log 2>&1
  args:
    chdir: "{{ playbook_path }}"
  register: lsf_predeploy_test_result
  changed_when: false
  failed_when: lsf_predeploy_test_result.rc != 0
  ignore_errors: no
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"
  async: 3600
  poll: 5

- name: Run LSF Deploy
  ansible.builtin.shell: >
    ansible-playbook -f 32 -i lsf-inventory lsf-deploy.yml >> deploy.log 2>&1
  args:
    chdir: "{{ playbook_path }}"
  register: lsf_deploy_test_result
  changed_when: false
  failed_when: lsf_deploy_test_result.rc != 0
  ignore_errors: no
  delegate_to: "{{ lsf_deployer_hostname }}.comp.com"
  async: 3600
  poll: 5

# - name: Run LSF Deploy with environment
#   ansible.builtin.shell: >
#     ansible-playbook -f 32 -i lsf-inventory lsf-deploy.yml >> deploy.log 2>&1
#   args:
#     chdir: "{{ playbook_path }}"
#     executable: /bin/bash
#   environment:
#     PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH }}"
#   register: lsf_deploy_test_result
#   changed_when: false
#   failed_when: lsf_deploy_test_result.rc != 0
#   ignore_errors: no
#   delegate_to: "{{ lsf_deployer_hostname }}.comp.com"
#   async: 3600
#   poll: 5