---
- name: Check if domain exists in /etc/resolv.conf
  ansible.builtin.shell: grep -Fxq "search {{ dns_domain }}" /etc/resolv.conf
  register: search_check
  ignore_errors: yes

- name: When line not found, fix /etc/resolv.conf
  block:
    - name: Backup original /etc/resolv.conf
      ansible.builtin.copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bkp
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Make /etc/resolv.conf editable
      ansible.builtin.command: chattr -i /etc/resolv.conf

    - name: Update /etc/resolv.conf with search line
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        state: present
        create: yes
        line: "search {{ dns_domain }}"

    - name: Make /etc/resolv.conf immutable again
      ansible.builtin.command: chattr +i /etc/resolv.conf
  when: search_check.rc != 0

- name: restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted